### ISSUE TITLE
Hexo g 后报错

### ISSUE THREAD

**Issue by NoctuG** [Yuameshi/hexo-theme-mdx#1]
````bash
[MDx]   [INFO]  Checking configurations...
ERROR {
  err: TypeError: Cannot read properties of undefined (reading 'path')
      at C:\Users\21225\OneDrive\Documents\mlou\node_modules\hexo-theme-mdx\scripts\index.js:5:64
      at C:\Users\21225\OneDrive\Documents\mlou\node_modules\hexo\lib\hexo\index.js:305:14
      at tryCatcher (C:\Users\21225\OneDrive\Documents\mlou\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\21225\OneDrive\Documents\mlou\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\21225\OneDrive\Documents\mlou\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromise0 (C:\Users\21225\OneDrive\Documents\mlou\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\21225\OneDrive\Documents\mlou\node_modules\bluebird\js\release\promise.js:729:18)
      at _drainQueueStep (C:\Users\21225\OneDrive\Documents\mlou\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (C:\Users\21225\OneDrive\Documents\mlou\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Users\21225\OneDrive\Documents\mlou\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\21225\OneDrive\Documents\mlou\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (node:internal/timers:466:21)
} Script load failed: %s n
``````````
初次安装，不知道是什么原因，正常使用无问题但报错太长影响感官，故有此问，期望作者能给予解答，谢谢 :)

**Comment by yuameshi** [comment]
检查一下是否安装hexo-generator-search并正确配置(包括_config.yml和_config.mdx.yml)，若不行则提供一个示例仓库我来看看

**Comment by NoctuG** [comment]
> 检查一下是否安装hexo-generator-search并正确配置(包括_config.yml和_config.mdx.yml)，若不行则提供一个示例仓库我来看看

已解决，错误发生原因是 search中  `field` 错误填写为 `field: _post` ，感谢您的回复 👍

**Comment by yuameshi** [comment]
也感谢您支持hexo-theme-mdx
